# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bomberman.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'bomberman.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62omberman.proto\x12\tbomberman\"y\n\x06Packet\x12.\n\x0cjoin_request\x18\x01 \x01(\x0b\x32\x16.bomberman.JoinRequestH\x00\x12\x34\n\x0fserver_response\x18\x02 \x01(\x0b\x32\x19.bomberman.ServerResponseH\x00\x42\t\n\x07payload\" \n\x0bJoinRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"A\n\x0eServerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bomberman_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKET']._serialized_start=30
  _globals['_PACKET']._serialized_end=151
  _globals['_JOINREQUEST']._serialized_start=153
  _globals['_JOINREQUEST']._serialized_end=185
  _globals['_SERVERRESPONSE']._serialized_start=187
  _globals['_SERVERRESPONSE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
